#!/usr/bin/env bash
#
# discover-interfaces.sh
# Production Open vSwitch interface discovery script
#
# In TEST_MODE it includes dummy/test interfaces for CI/CD pipelines.

set -euo pipefail

LOG_PREFIX="[OVS-DISCOVERY]"
CONFIG_FILE="/etc/ovs/interface-config.conf"

echo -e "\e[0;32m[$(date '+%F %T')]${LOG_PREFIX}\e[0m Starting OVS Interface Discovery"
echo

echo -e "\e[0;34m=== Current Network Configuration ===\e[0m"
echo

echo -e "\e[1;33mBridges:\e[0m"
brctl show 2>/dev/null || echo "(bridge-utils not installed)"
echo

echo -e "\e[1;33mOVS Bridges:\e[0m"
ovs-vsctl show || echo "(Open vSwitch not installed or not running)"
echo

echo -e "\e[1;33mInterface Status:\e[0m"
ip -d link show
echo

# Default environment variables
: "${MANAGEMENT_INTERFACE:=eth0}"
: "${BRIDGE_NAME:=br0}"
: "${TEST_MODE:=false}"
: "${FORCE:=false}"

# Collect candidate interfaces
if [[ "$TEST_MODE" == "true" ]]; then
  echo "[INFO] Test mode enabled — including dummy/test interfaces"
  CANDIDATE_INTERFACES=$(ip -o link show | awk -F': ' '{print $2}' \
    | grep -v '^lo$' \
    | grep -v "^$MANAGEMENT_INTERFACE$")
else
  CANDIDATE_INTERFACES=$(ip -o link show | awk -F': ' '{print $2}' \
    | grep -v '^lo$' \
    | grep -v "^$MANAGEMENT_INTERFACE$" \
    | grep -v '^docker' \
    | grep -v '^br-')
fi

TOTAL_INTERFACES=$(echo "$CANDIDATE_INTERFACES" | wc -w)

echo -e "\e[0;32m[$(date '+%F %T')]${LOG_PREFIX}\e[0m Discovering network interfaces..."
echo -e "\e[0;32m[$(date '+%F %T')]${LOG_PREFIX}\e[0m Found $TOTAL_INTERFACES available interfaces (excluding $MANAGEMENT_INTERFACE)"
echo

if [[ $TOTAL_INTERFACES -lt 2 && "$FORCE" != "true" ]]; then
  echo -e "\e[0;31m[$(date '+%F %T')] ERROR:\e[0m Need at least 2 interfaces for switching. Found: $TOTAL_INTERFACES"
  exit 1
fi

SWITCH_INTERFACES=($CANDIDATE_INTERFACES)

# Write config file
sudo mkdir -p "$(dirname "$CONFIG_FILE")"

cat <<EOF | sudo tee "$CONFIG_FILE" >/dev/null
# Auto-generated by discover-interfaces.sh
MANAGEMENT_INTERFACE=$MANAGEMENT_INTERFACE
BRIDGE_NAME=$BRIDGE_NAME
SWITCH_INTERFACES=(${SWITCH_INTERFACES[*]})
TOTAL_INTERFACES=$TOTAL_INTERFACES
EOF

echo "✅ Configuration file written to $CONFIG_FILE"
echo

cat "$CONFIG_FILE"
echo

exit 0