name: OVS Interface Discovery Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- Full OVS test on Ubuntu host ---
  test-on-ubuntu:
    runs-on: self-hosted
    steps:
      - name: Fix runner workspace permissions
        run: sudo chown -R $USER:$USER /home/$USER/actions-runner/_work

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        run: |
          sudo apt update
          sudo apt install -y openvswitch-switch bridge-utils iproute2 ethtool

      - name: Add dummy interfaces
        run: |
          sudo ip link add veth0 type veth peer name veth1
          sudo ip link set veth0 up
          sudo ip link set veth1 up

      - name: Run discover-interfaces.sh
        run: |
          chmod +x ./scripts/discover-interfaces.sh
          ./scripts/discover-interfaces.sh

  # --- Sanity check inside Fedora ---
  test-on-fedora:
    runs-on: self-hosted
    container:
      image: fedora:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (Fedora)
        run: |
          dnf install -y iproute net-tools ethtool
          # OVS skipped: needs --privileged
      - name: Add dummy interfaces
        run: |
          ip link add veth0 type veth peer name veth1
          ip link set veth0 up
          ip link set veth1 up
      - name: Run discover-interfaces.sh (Fedora sanity check)
        run: |
          chmod +x ./scripts/discover-interfaces.sh
          ./scripts/discover-interfaces.sh || echo "Expected limited functionality in container"

  # --- Sanity check inside CentOS Stream 9 ---
  test-on-centos:
    runs-on: self-hosted
    container:
      image: quay.io/centos/centos:stream9
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (CentOS)
        run: |
          dnf install -y iproute net-tools ethtool
          # OVS skipped: needs --privileged
      - name: Add dummy interfaces
        run: |
          ip link add veth0 type veth peer name veth1
          ip link set veth0 up
          ip link set veth1 up
      - name: Run discover-interfaces.sh (CentOS sanity check)
        run: |
          chmod +x ./scripts/discover-interfaces.sh
          ./scripts/discover-interfaces.sh || echo "Expected limited functionality in container"
