name: Series Multi-OS Discover Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  series-test:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # adjust for VM startup time

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Environment Variables
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export MANAGEMENT_INTERFACE=eth0
          export TEST_MODE=true
          export FORCE=true
          mkdir -p ./logs

      - name: Install Host Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            qemu-kvm libvirt-clients libvirt-daemon-system cloud-image-utils sshpass \
            openvswitch-switch openvswitch-common bridge-utils net-tools tcpdump ethtool curl jq git

      - name: Run Test on Ubuntu Host
        run: |
          bash ./tests/test-discover-harness.sh
          cp ./tests/logs/*.log ./logs/ubuntu.log

      - name: Run Test in Fedora VM
        run: |
          FEDORA_IMG=fedora.qcow2
          if [ ! -f $FEDORA_IMG ]; then
            curl -LO https://download.fedoraproject.org/pub/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-40-1.6.x86_64.qcow2
          fi
          cp $FEDORA_IMG fedora-test.qcow2
          qemu-system-x86_64 -m 2048 -smp 2 -drive file=fedora-test.qcow2,format=qcow2 \
            -net nic -net user,hostfwd=tcp::2222-:22 -nographic &
          VM_PID=$!
          until nc -z localhost 2222; do sleep 5; done
          sshpass -p fedora ssh -o StrictHostKeyChecking=no -p 2222 fedora@localhost 'bash -s' < ./tests/test-discover-harness.sh
          scp -P 2222 fedora@localhost:/path/to/logs/*.log ./logs/fedora.log
          kill $VM_PID
          wait $VM_PID 2>/dev/null || true

      - name: Run Test in CentOS VM
        run: |
          CENTOS_IMG=centos-stream.qcow2
          if [ ! -f $CENTOS_IMG ]; then
            curl -LO https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-9-GenericCloud-9.2.0.x86_64.qcow2
          fi
          cp $CENTOS_IMG centos-test.qcow2
          qemu-system-x86_64 -m 2048 -smp 2 -drive file=centos-test.qcow2,format=qcow2 \
            -net nic -net user,hostfwd=tcp::2223-:22 -nographic &
          VM_PID=$!
          until nc -z localhost 2223; do sleep 5; done
          sshpass -p centos ssh -o StrictHostKeyChecking=no -p 2223 centos@localhost 'bash -s' < ./tests/test-discover-harness.sh
          scp -P 2223 centos@localhost:/path/to/logs/*.log ./logs/centos.log
          kill $VM_PID
          wait $VM_PID 2>/dev/null || true

      - name: Upload All Logs
        uses: actions/upload-artifact@v4
        with:
          name: ovs-discover-test-results
          path: ./logs/*.log