name: Test discover-interfaces.sh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-discover:
    name: Run tests on ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu:22.04, fedora:40, quay.io/centos/centos:stream9]

    container:
      image: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          if command -v apt-get >/dev/null; then
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
              iproute2 bridge-utils ethtool sudo git iputils-ping
          elif command -v dnf >/dev/null; then
            dnf install -y iproute bridge-utils ethtool sudo git iputils
          elif command -v yum >/dev/null; then
            yum install -y iproute bridge-utils ethtool sudo git iputils
          fi

      - name: Setup dummy interfaces
        run: |
          modprobe dummy || true
          ip link add dummy0 type dummy || true
          ip link add dummy1 type dummy || true
          ip link set dummy0 up
          ip link set dummy1 up
          ip addr add 10.123.0.1/24 dev dummy0
          ip addr add 10.123.0.2/24 dev dummy1
          ip link show

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Run harness tests
        run: |
          cd tests
          chmod +x test-discover-harness.sh
          ./test-discover-harness.sh

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: ovs-discover-test-results
          path: tests/*.log
