name: Test Discover OVS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-discover:
    strategy:
      matrix:
        os: [ubuntu:22.04, fedora:40, quay.io/centos/centos:stream9]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Environment Variables
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export MANAGEMENT_INTERFACE=eth0
          export TEST_MODE=true
          export FORCE=true

      - name: Install Dependencies
        run: |
          if command -v apt-get >/dev/null; then
            apt-get update -y -qq
            DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
              openvswitch-switch \
              openvswitch-common \
              bridge-utils \
              net-tools \
              tcpdump \
              ethtool \
              curl \
              jq \
              git
          elif command -v dnf >/dev/null; then
            dnf install -y -q openvswitch bridge-utils net-tools tcpdump ethtool curl jq git
          elif command -v yum >/dev/null; then
            yum install -y -q openvswitch bridge-utils net-tools tcpdump ethtool curl jq git
          fi

      - name: Verify Dependencies
        run: |
          echo "Checking installed packages..."
          for pkg in openvswitch-switch openvswitch-common bridge-utils net-tools tcpdump ethtool curl jq git; do
            if command -v $pkg >/dev/null 2>&1 || dpkg -l | grep -qw $pkg; then
              echo "$pkg installed"
            else
              echo "$pkg NOT installed"
            fi
          done

      - name: Setup Dummy Interfaces
        run: |
          modprobe dummy || true
          ip link add dummy0 type dummy || true
          ip link add dummy1 type dummy || true
          ip link set dummy0 up
          ip link set dummy1 up
          ip addr add 10.123.0.1/24 dev dummy0
          ip addr add 10.123.0.2/24 dev dummy1

      - name: Run Interface Discovery Test
        run: |
          TEST_MODE=true FORCE=true bash ./tests/test-discover-harness.sh

      - name: Display Detected Interfaces Summary
        run: |
          echo -e "\n=== Summary of Detected Interfaces on ${{ matrix.os }} ==="
          if [[ -f /etc/ovs/interface-config.conf ]]; then
            grep -E '^SWITCH_INTERFACES=' /etc/ovs/interface-config.conf
          else
            echo "No configuration file found. Discovery may have failed."
          fi
          echo "=========================================================="

      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: ovs-discover-test-results-${{ matrix.os }}
          path: tests/logs/*.log