name: Test Discover OVS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-discover:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Environment Variables
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export MANAGEMENT_INTERFACE=eth0
          export TEST_MODE=true
          export FORCE=true

      - name: Update apt repositories
        run: sudo apt-get update -y -qq

      - name: Install Dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
            openvswitch-switch \
            openvswitch-common \
            bridge-utils \
            net-tools \
            tcpdump \
            ethtool \
            curl \
            jq \
            git

      - name: Verify Dependencies
        run: |
          echo "Checking installed packages..."
          for pkg in openvswitch-switch openvswitch-common bridge-utils net-tools tcpdump ethtool curl jq git; do
            dpkg -l | grep -qw $pkg && echo "$pkg installed" || echo "$pkg NOT installed"
          done

      - name: Setup Dummy Interfaces
        run: |
          sudo modprobe dummy || true
          sudo ip link add dummy0 type dummy || true
          sudo ip link add dummy1 type dummy || true
          sudo ip link set dummy0 up
          sudo ip link set dummy1 up
          sudo ip addr add 10.123.0.1/24 dev dummy0
          sudo ip addr add 10.123.0.2/24 dev dummy1

      - name: Run Interface Discovery Test
        run: |
          sudo TEST_MODE=true FORCE=true bash ./scripts/discover-interfaces.sh