name: Test Discover OVS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-discover:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # adjust if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Environment Variables
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export MANAGEMENT_INTERFACE=eth0

      - name: Update apt repositories
        run: sudo apt-get update -y -qq

      - name: Install Dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
            openvswitch-switch \
            openvswitch-common \
            bridge-utils \
            net-tools \
            tcpdump \
            ethtool \
            curl \
            jq \
            git

      - name: Verify Dependencies
        run: |
          echo "Checking installed packages..."
          for pkg in openvswitch-switch openvswitch-common bridge-utils net-tools tcpdump ethtool curl jq git; do
            dpkg -l | grep -qw $pkg && echo "$pkg installed" || echo "$pkg NOT installed"
          done

      - name: Run Interface Discovery Test
        run: |
          sudo bash ./discover-interfaces.sh
