name: OVS Interface Discovery Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # allows manual trigger

jobs:
  test-discover-interfaces:
    runs-on: self-hosted
    steps:
      - name: Fix runner workspace permissions
        run: sudo chown -R $USER:$USER /home/$USER/actions-runner/_work

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./scripts/discover-interfaces.sh

      - name: Run discover-interfaces.sh
        run: ./scripts/discover-interfaces.sh

  test-on-fedora:
    runs-on: self-hosted
    container:
      image: fedora:latest
    steps:
      - uses: actions/checkout@v4
      - run: dnf install -y iproute net-tools
      - run: chmod +x ./scripts/discover-interfaces.sh
      - run: ./scripts/discover-interfaces.sh

  test-on-centos:
    runs-on: self-hosted
    container:
      image: quay.io/centos/centos:stream9
    steps:
      - uses: actions/checkout@v4
      - run: dnf install -y iproute net-tools
      - run: chmod +x ./scripts/discover-interfaces.sh
      - run: ./scripts/discover-interfaces.sh
