name: OVS Layer 2 Switch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    name: Run OVS Tests on multiple OSs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-image:
          - centos-9-stream
          - ubuntu-24.04
          - fedora-39
    env:
      SSH_PORT: $((2220 + RANDOM % 100))
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y qemu-utils curl

      - name: Ensure vm-images and logs directories exist
        run: mkdir -p vm-images logs

      - name: Set IMAGE_URL dynamically based on OS
        id: set_image
        run: |
          case "${{ matrix.os-image }}" in
            "centos-9-stream")
              BASE_URL="https://cloud.centos.org/centos/9-stream/x86_64/images/"
              IMAGE_FILE_NAME=$(curl -s "$BASE_URL" | \
                grep -Eo 'CentOS-Stream-GenericCloud-9-[^"]*\.qcow2' | \
                grep -vE 'SHA256|CHECKSUM' | sort -V | tail -n1)
              ;;
            "ubuntu-24.04")
              BASE_URL="https://cloud-images.ubuntu.com/releases/24.04/release/"
              # First try base or -disk-kvm.img
              IMAGE_FILE_NAME=$(curl -s "$BASE_URL" | \
                grep -Eo 'ubuntu-24\.04-server-cloudimg-amd64(-disk-kvm)?\.img' | \
                sort -V | head -n1)

              # If still empty, fallback to any amd64 .img (exclude checksums/manifests)
              if [[ -z "$IMAGE_FILE_NAME" ]]; then
                IMAGE_FILE_NAME=$(curl -s "$BASE_URL" | \
                  grep -Eo 'ubuntu-24\.04-server-cloudimg-amd64[^"]*\.img' | \
                  grep -vE '\.manifest|\.sha256|\.txt' | head -n1)
              fi
              ;;
            "fedora-39")
              BASE_URL="https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/"
              IMAGE_FILE_NAME=$(curl -s "$BASE_URL" | \
                grep -Eo 'Fedora-Cloud-Base-[0-9]+-[0-9]+\.x86_64\.qcow2' | sort -V | tail -n1)
              ;;
            *)
              echo "Unsupported OS: ${{ matrix.os-image }}"
              exit 1
              ;;
          esac

          if [[ -z "$IMAGE_FILE_NAME" ]]; then
            echo "❌ Could not determine latest image for ${{ matrix.os-image }}"
            echo "Debug: Showing available files from $BASE_URL ..."
            curl -s "$BASE_URL" | grep -E '\.img|\.qcow2' | head -20
            exit 1
          fi

          IMAGE_URL="${BASE_URL}${IMAGE_FILE_NAME}"
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV
          echo "Latest image for ${{ matrix.os-image }}: $IMAGE_FILE_NAME"

      - name: Download and prepare VM
        run: |
          IMAGE_FILE="vm-images/$(basename $IMAGE_URL)"
          WORK_IMAGE="vm-images/test-${{ matrix.os-image }}-$(date +%s).qcow2"

          if [[ ! -f "$IMAGE_FILE" ]]; then
            echo "Downloading VM image for ${{ matrix.os-image }}..."
            curl -L --fail --retry 3 --retry-delay 5 -o "$IMAGE_FILE" "$IMAGE_URL"
          else
            echo "Using cached image: $IMAGE_FILE"
          fi

          echo "Verifying image..."
          qemu-img info "$IMAGE_FILE" || { echo "❌ Invalid image file"; exit 1; }

          cp "$IMAGE_FILE" "$WORK_IMAGE"
          qemu-img resize "$WORK_IMAGE" 10G

          echo "VM_IMAGE=$WORK_IMAGE" >> $GITHUB_ENV
          echo "✅ Prepared VM image: $WORK_IMAGE"

      - name: Sanitize shell scripts
        run: |
          find scripts tests -type f -name "*.sh" -exec sed -i 's/[""]/"/g' {} +
          find scripts tests -type f -name "*.sh" -exec sed -i "s/[‘’]/'/g" {} +
          find scripts tests -type f -name "*.sh" -exec sed -i 's/[^\x00-\x7F]/ /g' {} +

      - name: Run discovery and switch tests
        run: |
          set -e
          LOG_FILE=logs/test-${{ matrix.os-image }}.log
          sudo bash ./tests/test-discover-harness.sh > "$LOG_FILE" 2>&1

      - name: Upload test log artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ matrix.os-image }}
          path: logs/test-${{ matrix.os-image }}.log