on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Debug file presence
        run: |
          echo "Listing contents of the working directory:"
          ls -al
          echo "Listing contents of the 'scripts' directory:"
          ls -al scripts

      - name: List all files
        run: find . -name "*.sh"

      - name: Setup Test Environment
        run: |
          if [[ ! -f "scripts/discover-interfaces.sh" ]]; then
            echo "❌ ERROR: scripts/discover-interfaces.sh not found!"
            exit 1
          fi
          # Other setup steps...

      - name: Make script executable
        run: chmod +x scripts/discover-interfaces.sh

      - name: Test on Ubuntu Host
        run: |
          # Your test commands here...
          echo "Environment Variables:"
          printenv
